# Generated by Django 4.2.3 on 2023-08-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comments_followers_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
