# Generated by Django 4.2.3 on 2023-08-10 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_follow_follower_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
