# Generated by Django 4.2.3 on 2023-08-16 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_delete_comment_remove_like_liked_like_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
    ]
