# Generated by Django 4.2.3 on 2023-07-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ManyToManyField(blank=True, null=True, related_name='item_bid', to='auctions.listing'),
        ),
    ]
