# Generated by Django 4.2.3 on 2023-07-20 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bid_listing_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
