# Generated by Django 4.2.3 on 2023-07-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
