# Generated by Django 4.2.3 on 2023-07-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
