# Generated by Django 4.2.3 on 2023-07-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_comment_user_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('OPEN', 'Open')], default='OPEN', max_length=7),
        ),
    ]
