# Generated by Django 4.2.3 on 2023-07-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listing_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
