# Generated by Django 4.2.3 on 2023-07-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='item',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
    ]
